### ISSUE TITLE
Software Note Citation

### ISSUE THREAD

**Issue by LiNk-NY** [waldronlab/HGNChelper#10]
I couldn't find a reference to the paper in the package. Perhaps this could go in `inst/CITATION`. 
Is there a published citation? I see this: https://www.biorxiv.org/content/10.1101/2020.09.16.300632v1

**Comment by lwaldron** [comment]
Citation to F1000Research added by https://github.com/waldronlab/HGNChelper/commit/55722a80d75bf0e0ea7a086dcfbfdae7e682ca01
