### ISSUE TITLE
Can HGNChelper convert the gene symbols from mouse to human?

### ISSUE THREAD

**Issue by lincj1994** [waldronlab/HGNChelper#17]
Hi. Thanks for developing such a nice tool. I'm wondering if this package can convert the gene symbols from mouse to human?
Thanks.

**Comment by LiNk-NY** [comment]
I'm not sure this is possible but Levi @lwaldron is the expert

**Comment by lwaldron** [comment]
Sorry, it won't help with that. I'd recommend trying the [biomaRt](https://bioconductor.org/packages/biomaRt/) package.
