### ISSUE TITLE
update version on CRAN

### ISSUE THREAD

**Issue by LiNk-NY** [waldronlab/HGNChelper#21]
The version of HGNChelper should be updated on CRAN as it has some bugs: 

https://github.com/waldronlab/HGNChelper/issues/20

cc: @lwaldron

**Comment by lwaldron** [comment]
Done, thanks @LiNk-NY

**Comment by lwaldron** [comment]
Actually I'll leave open until 0.8.13 actually appears on CRAN.

**Comment by lwaldron** [comment]
Done, ended up being 0.8.14
