### ISSUE TITLE
Why isn't Pzp recognized as valid?

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/HGNChelper#4]
See this line in the vignette about mouse gene symbols:

https://github.com/waldronlab/HGNChelper/blob/dc8d088bd1dfe5e70d8f174e44a75e87f46f0752/vignettes/index.Rmd#L51

**Comment by lwaldron** [comment]
Seems to be fixed by https://github.com/waldronlab/HGNChelper/commit/a37d8779be4239e73d13e39de33c02b3388254d7

Will close with the addition of a unit test by @shbrief .

**Comment by shbrief** [comment]
**Additional issues with mouse gene symbol conversion** 
- 'Symbol' and 'Approved.Symbol' columns were mixed for withdrawn status entries
 - Some aliases have uppercase in the middle if they are mixture of number and alphabet 

**Debug plan**
- making additional column in the `mouse.table` with all lowercases
- compare aliases with both lowercase version and correct version of gene symbols

**Comment by shbrief** [comment]
- First issue fixed by `d3ff5a6`
- Second issue seems pretty rare and we decide to leave it for now.
