### ISSUE TITLE
unit test for chromosome option

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/HGNChelper#9]
@Aggarwal-Ayush  has added examples, e.g. https://github.com/waldronlab/HGNChelper/blob/be6f7a901335948bcba043a596f8fc76b9048e4d/R/checkGeneSymbols.R#L62

Now create formal unit tests in the tests/ directory to make sure the expected behavior occurs.

**Comment by shbrief** [comment]
Chromosome argument related unit tests were moved/updated in `tests/testthat/test_checkGeneSymbols.R` and confirmed by GHA R-CMD-check. 6e55d804565d14dbbcdb155bed546c036d507215
